- name: download fornax-s3-subsets
  git:
    repo: https://github.com/fornax-navo/fornax-s3-subsets.git
    dest: /home/ec2-user/fornax-s3-subsets
    clone: yes
    update: no

- name: install the conda environment
  command:
    argv:
      - /bin/bash
      - -l
      - -c
      - cd /home/ec2-user/fornax-s3-subsets-ansible/subset && /home/ec2-user/mambaforge/bin/mamba env create -f bench_environment.yml

- name: create mount directory
  file:
    path: /home/ec2-user/s3
    state: directory
    owner: ec2-user
    group: ec2-user
    mode: 0750
